### ISSUE TITLE
ImportError with export_to_quod_libet.py

### ISSUE THREAD

**Issue by VenomQuartz** [Tamriel/quod_libet_import_itunes_ratings#2]
During the step where I run export_to_quod_libet.py, I get this: 

> Traceback (most recent call last):
>   File "export_to_quod_libet.py", line 10, in <module>
>     songs = cPickle.load(f)
> ImportError: No module named quodlibet.formats.mp3

I _am_ using `python export_to_quod_libet.py`, instead of `python2 export_to_quod_libet.py`. This is because when I used `python2 export_to_quod_libet.py`, I got a bash error that said that the python2 command was not found, and I was told that `python` would be an acceptable substitute.

**Comment by Tamriel** [comment]
You have quod libet installed?

**Comment by VenomQuartz** [comment]
Yeah, of course.

**Comment by Tamriel** [comment]
You are right. Linux and Mac user get the needed dependencies while installing, Windows users not.
So I updated the Readme file:
Windows users: You need the quod libet dependencies. For that, download the  [quodlibet-3.6-win-sdk.tar.xz](http://quodlibet.readthedocs.io/en/latest/downloads.html), extract it with [7zip](http://7-zip.org/) and install it somehow.

**Comment by VenomQuartz** [comment]
That's great! I'm using OS X, though, and I'm still having this problem.

**Comment by Tamriel** [comment]
Ok, try this:
Download [quodlibet-3.6.2.tar.gz](http://quodlibet.readthedocs.io/en/latest/downloads.html#source-logo-release-tarballs) and extract it. Open a terminal, navigate to that folder with `cd` + drag'n'drop that folder into the terminal. Run `python setup.py install`.
Now it should work.

**Comment by VenomQuartz** [comment]
I tried installing Quodlibet the way you suggested, and I'm having an issue with _that_. Would there be any alternative way to do this? I'm really having a lot of trouble figuring out the install issue.

In case it's useful, here's what the read-out is when I tried to install. 

> Username:quodlibet-3.6.2 Username$ python setup.py install
> running install
> running build
> running build_py
> running build_scripts
> running build_mo
> error: [Errno 2] No such file or directory

Also, in case it is useful as well, I originally installed Quodlibet through the zip file on their download page.

**Comment by Tamriel** [comment]
I don't know a solution - you may create an issue at the quod libet tracker.
Or copy paste the itunes export to a linux system and import in quod libet there. Then copy paste the quod libet files to your mac. I think this is even doable with a live operating system, e.g. run ubuntu from usb stick.
